import { Package, Leaf, Droplet, Zap } from "lucide-react"

export const products = [
  {
    id: 1,
    name: "Bio Carry Bags",
    description: "Biodegradable carry bags for eco-conscious packaging",
    image: "/pa1.jpg",
    category: "Customizable",
    icon: Package,
    customizable: true,
    details:
      "Premium biodegradable carry bags made from renewable resources. Perfect for retail, food service, and e-commerce businesses focused on sustainability.",
    images: ["/pa1.jpg", "/pa2.jpg", "/pa3.jpg"],
    specs: ["100% Biodegradable / Compostable options"],
  },
  {
    id: 15,
    name: "Pouches",
    description: "Customizable pouches for retail and food packaging",
    image: "/pouch.jpg",
    category: "Customizable",
    icon: Package,
    customizable: true,
    details:
      "Durable, printable pouches suitable for snacks, powders, and retail products with various size and closure options.",
    images: ["/pouch.jpg"],
    specs: ["Material: PP/LDPE/BOPP options"],
  },
  {
    id: 2,
    name: "Brown Bag & Covers",
    description: "Brown Paper Bags and Paper Covers for natural packaging",
    image: "/brown-kraft-paper-bags-covers.jpg",
    category: "Customizable",
    icon: Leaf,
    customizable: true,
    details:
      "Durable, high-quality brown paper bags and complementing covers/wraps. Ideal for takeaway food, retail goods, and general wrapping purposes.",
    images: [
      "/WhatsApp Image 2025-11-05 at 14.34.21_2cc2ab39.jpg",
      "/WhatsApp Image 2025-11-05 at 14.34.21_cbce949a.jpg",
      "/WhatsApp Image 2025-11-05 at 14.34.22_af780868.jpg",
    ],
    specs: ["Material: High-grade Kraft Paper"],
  },
  {
    id: 3,
    name: "Bio Paper Cups & Containers",
    description: "Eco-friendly paper cups and containers with plant-based lining",
    image: "/IMG-20251105-WA0006.jpg",
    category: "Customizable",
    icon: Package,
    customizable: true,
    details: "Disposable paper cups and containers that are a sustainable alternative to traditional plastic, suitable for both hot and cold items.",
    images: [
      "/IMG-20251105-WA0006.jpg",
      "/IMG-20251105-WA0007.jpg",
      "/IMG-20251105-WA0008.jpg",
      "/IMG-20251105-WA0009.jpg",
      "/IMG-20251105-WA0010.jpg",
    ],
    specs: ["Plant-Based PLA or Aqua-Coating"],
  },
  {
    id: 4,
    name: "PP, LDPE & BOPP Pouches",
    description: "Flexible plastic pouches for versatile product packaging",
    image: "/plastic-pouches-pp-ldpe-bopp.jpg",
    category: "Customizable",
    icon: Droplet,
    customizable: true,
    details: "High-clarity and moisture-resistant pouches for packaging snacks, powders, cosmetics, and other consumer goods.",
    images: ["/plastic-pouches-pp-ldpe-bopp.jpg", "/plastic-pouches-packaging.jpg", "/flexible-film-pouches.jpg"],
    specs: ["High Barrier Properties (Moisture/Air)"],
  },
  {
    id: 5,
    name: "Aluminium Containers",
    description: "Aluminum foil containers and rolls for food handling",
    image: "/IMG-20251106-WA0008.jpg",
    category: "Containers",
    icon: Package,
    customizable: false,
    details:
      "Versatile aluminum products perfect for cooking, freezing, transporting, and serving food, offering heat resistance and flavor preservation.",
    images: [
      "/IMG-20251106-WA0008.jpg",
      "/IMG-20251106-WA0009.jpg",
      "/IMG-20251106-WA0010.jpg",
      "/IMG-20251106-WA0011.jpg",
    ],
    specs: ["Leak-resistant and Oil-Proof"],
  },
  {
    id: 6,
    name: "PP Food Containers",
    description: "Food-grade PP containers for takeaway and storage",
    image: "/IMG-20251105-WA0016.jpg",
    category: "Containers",
    icon: Droplet,
    customizable: false,
    details: "Durable, stackable, and leak-resistant PP containers ideal for restaurants, cloud kitchens, and catering.",
    images: [
      "/IMG-20251105-WA0016.jpg",
      "/IMG-20251105-WA0017.jpg",
      "/IMG-20251105-WA0018.jpg",
      "/IMG-20251105-WA0019.jpg",
    ],
    specs: ["Material: PP (Food Grade)"],
  },
  {
    id: 13,
    name: "PP Juice Cups",
    description: "Disposable PP cups for juices and cold beverages",
    image: "/IMG-20251106-WA0003.jpg",
    category: "Containers",
    icon: Droplet,
    customizable: false,
    details: "Crystal-clear, sturdy PP cups suitable for juice, shakes, and iced beverages.",
    images: [
      "/IMG-20251106-WA0003.jpg",
      "/IMG-20251106-WA0004.jpg",
      "/IMG-20251106-WA0005.jpg",
      "/IMG-20251106-WA0006.jpg",
    ],
    specs: ["Material: PP (Food Grade)"],
  },
  {
    id: 14,
    name: "PP Sweet Boxes",
    description: "Attractive PP boxes designed for sweets and gifting",
    image: "/001.jpg",
    category: "Containers",
    icon: Droplet,
    customizable: false,
    details: "Presentable and hygienic packaging for sweets and confectionery with good visibility and protection.",
    images: [
      "/001.jpg",
      "/002.jpg",
      "/003.jpg",
      "/004.jpg",
      "/005.jpg",
      "/006.jpg",
    ],
    specs: ["Material: PP (Food Grade)"],
  },
  {
    id: 7,
    name: "PET Hinged Containers",
    description: "Clear PET hinged containers for secure, display-ready packaging",
    image: "/007.jpg",
    category: "Containers",
    icon: Package,
    customizable: false,
    details: "Highly transparent hinged containers ideal for salads, desserts, and takeaway items with excellent product visibility.",
    images: [
      "/007.jpg",
      "/008.jpg",
      "/009.jpg",
      "/010.jpg",
      "/011.jpg",
      "/012.jpg",
    ],
    specs: ["High Transparency (Crystal Clear)"],
  },
  {
    id: 16,
    name: "Dessert Cups",
    description: "Elegant dessert cups suitable for single-serve sweets and displays",
    image: "/IMG-20251106-WA0012.jpg",
    category: "Containers",
    icon: Package,
    customizable: false,
    details:
      "Crystal-clear dessert cups ideal for parfaits, mousse, and party servings with premium presentation.",
    images: [
      "/IMG-20251106-WA0012.jpg",
      "/IMG-20251106-WA0013.jpg",
      "/IMG-20251106-WA0014.jpg",
      "/IMG-20251106-WA0015.jpg",
      "/IMG-20251106-WA0016.jpg",
      "/IMG-20251106-WA0017.jpg",
      "/IMG-20251105-WA0032.jpg",
      "/IMG-20251105-WA0033.jpg",
      "/IMG-20251105-WA0034.jpg",
    ],
    specs: ["Food Grade PET"],
  },
  {
    id: 8,
    name: "Wooden Cutlery & Paper Straw",
    description: "Natural, disposable wooden utensils and paper drinking straws",
    image: "/wooden-cutlery-paper-straws.jpg",
    category: "Accessories",
    icon: Leaf,
    customizable: false,
    details: "Eco-friendly cutlery sets and beverage straws that provide a biodegradable alternative for catering, events, and takeaway food service.",
    images: ["/wooden-cutlery-paper-straws.jpg", "/wooden-cutlery-eco-friendly.jpg", "/placeholder.svg?height=400&width=400"],
    specs: ["Material: Natural Wood (Birch) and Paper"],
  },
  {
    id: 9,
    name: "Napkin Tissue Paper",
    description: "Hygienic and absorbent paper napkins and tissue products",
    image: "/napkin-tissue-paper.jpg",
    category: "Paper",
    icon: Package,
    customizable: false,
    details: "Essential disposable paper products for general hygiene, table service, and clean-up in restaurants, catering, and household settings.",
    images: [
      "/napkin-tissue-paper.jpg",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    specs: ["Ply: 1 Ply, 2 Ply, or 3 Ply options"],
  },
  {
    id: 10,
    name: "Areca Plates",
    description: "100% natural, biodegradable Areca leaf tableware",
    image: "/areca-bagasse-plates-natural-fiber.jpg",
    category: "Plates",
    icon: Leaf,
    customizable: false,
    details: "Sturdy and stylish plates, bowls, and trays made from fallen Areca palm leaves or sugarcane pulp (Bagasse).",
    images: [
      "/areca-bagasse-plates-natural-fiber.jpg",
      "/disposable-eco-friendly-plates-bowls-natural-fiber.jpg",
    ],
    specs: ["100% Natural, No Chemicals or Wax Lining"],
  },
  {
    id: 17,
    name: "Bagasse Plates",
    description: "Biodegradable Bagasse plates from sugarcane pulp",
    image: "/arpl1.jpg",
    category: "Plates",
    icon: Leaf,
    customizable: false,
    details: "Durable, heat-resistant, and compostable plates suitable for hot and cold foods.",
    images: [
      "/arpl1.jpg",
    ],
    specs: ["Microwave Safe, Compostable"],
  },
  {
    id: 11,
    name: "Hand Gloves & Bouffant Caps",
    description: "Disposable protective wear for hygiene and contamination control",
    image: "/hand-gloves-bouffant-caps.jpg",
    category: "Safety",
    icon: Zap,
    customizable: false,
    details: "Head and hand coverings essential for maintaining sanitary conditions in food service, healthcare, cleanrooms, and industrial environments.",
    images: [
      "/hand-gloves-bouffant-caps.jpg",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    specs: ["Gloves: Latex, Nitrile, Vinyl, or PE options"],
  },
  {
    id: 12,
    name: "Garbage Bags",
    description: "Waste disposal bags in various sizes and biodegradability options",
    image: "/garbage-bags-waste-management.jpg",
    category: "Bags",
    icon: Package,
    customizable: false,
    details: "Essential bags for collecting and disposing of garbage, offered in standard, oxo-biodegradable, and compostable types.",
    images: [
      "/garbage-bags-waste-management.jpg",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    specs: ["Biodegradable and Compostable Options Available"],
  },
]
