import { Package, Leaf, Droplet, Zap } from "lucide-react"

export const products = [
  {
    id: 1,
    name: "Bio Carry Bag & Pouches",
    description: "Biodegradable carry bags and pouches for eco-conscious packaging",
    image: "/biodegradable-carry-bags-pouches.jpg",
    category: "Customizable",
    icon: Package,
    customizable: true,
    details:
      "Premium biodegradable carry bags and pouches made from renewable resources. Perfect for retail, food service, and e-commerce businesses focused on sustainability.",
    images: ["/biodegradable-carry-bags-pouches.jpg", "/eco-friendly-carry-bags.jpg", "/biodegradable-pouches.jpg"],
    specs: ["100% Biodegradable / Compostable options"],
  },
  {
    id: 2,
    name: "Brown Bag & Covers",
    description: "Brown Paper Bags and Paper Covers for natural packaging",
    image: "/brown-kraft-paper-bags-covers.jpg",
    category: "Customizable",
    icon: Leaf,
    customizable: true,
    details:
      "Durable, high-quality brown paper bags and complementing covers/wraps. Ideal for takeaway food, retail goods, and general wrapping purposes.",
    images: ["/brown-kraft-paper-bags-covers.jpg", "/kraft-paper-bags.jpg", "/brown-paper-covers.jpg"],
    specs: ["Material: High-grade Kraft Paper"],
  },
  {
    id: 3,
    name: "Bio Paper Cups & Containers",
    description: "Eco-friendly paper cups and containers with plant-based lining",
    image: "/biodegradable-paper-cups-containers.jpg",
    category: "Customizable",
    icon: Package,
    customizable: true,
    details: "Disposable paper cups and containers that are a sustainable alternative to traditional plastic, suitable for both hot and cold items.",
    images: ["/biodegradable-paper-cups-containers.jpg", "/paper-cups-biodegradable.jpg", "/food-containers-compostable.jpg"],
    specs: ["Plant-Based PLA or Aqua-Coating"],
  },
  {
    id: 4,
    name: "PP, LDPE & BOPP Pouches",
    description: "Flexible plastic pouches for versatile product packaging",
    image: "/plastic-pouches-pp-ldpe-bopp.jpg",
    category: "Customizable",
    icon: Droplet,
    customizable: true,
    details: "High-clarity and moisture-resistant pouches for packaging snacks, powders, cosmetics, and other consumer goods.",
    images: ["/plastic-pouches-pp-ldpe-bopp.jpg", "/plastic-pouches-packaging.jpg", "/flexible-film-pouches.jpg"],
    specs: ["High Barrier Properties (Moisture/Air)"],
  },
  {
    id: 5,
    name: "Aluminium Container & Wraps",
    description: "Aluminum foil containers and rolls for food handling",
    image: "/aluminium-containers-wraps.jpg",
    category: "Containers",
    icon: Package,
    customizable: false,
    details:
      "Versatile aluminum products perfect for cooking, freezing, transporting, and serving food, offering heat resistance and flavor preservation.",
    images: ["/aluminium-containers-wraps.jpg", "/aluminium-food-containers.jpg"],
    specs: ["Leak-resistant and Oil-Proof"],
  },
  {
    id: 6,
    name: "Plastic Container & Juice Cups",
    description: "Standard plastic containers and disposable juice/cold drink cups",
    image: "/plastic-containers-juice-cups.jpg",
    category: "Containers",
    icon: Droplet,
    customizable: false,
    details: "Economical and convenient options for a wide range of food and beverage packaging, offering durability and clear visibility.",
    images: ["/plastic-containers-juice-cups.jpg", "/clear-plastic-cups.jpg", "/disposable-juice-containers.jpg"],
    specs: ["Material: Food-Grade Plastic (e.g., PP, PS)"],
  },
  {
    id: 7,
    name: "PET Container & Dessert Cups",
    description: "Clear PET packaging for beverages and elegant dessert presentation",
    image: "/pet-containers-dessert-cups.jpg",
    category: "Containers",
    icon: Package,
    customizable: false,
    details: "Highly transparent containers and small decorative cups used for cold-pressed juices, salads, and single-serve desserts like mousse and parfaits.",
    images: ["/pet-containers-dessert-cups.jpg", "/pet-dessert-containers.jpg", "/transparent-food-cups.jpg"],
    specs: ["High Transparency (Crystal Clear)"],
  },
  {
    id: 8,
    name: "Wooden Cutlery & Paper Straw",
    description: "Natural, disposable wooden utensils and paper drinking straws",
    image: "/wooden-cutlery-paper-straws.jpg",
    category: "Accessories",
    icon: Leaf,
    customizable: false,
    details: "Eco-friendly cutlery sets and beverage straws that provide a biodegradable alternative for catering, events, and takeaway food service.",
    images: ["/wooden-cutlery-paper-straws.jpg", "/wooden-cutlery-eco-friendly.jpg", "/placeholder.svg?height=400&width=400"],
    specs: ["Material: Natural Wood (Birch) and Paper"],
  },
  {
    id: 9,
    name: "Napkin Tissue Paper",
    description: "Hygienic and absorbent paper napkins and tissue products",
    image: "/napkin-tissue-paper.jpg",
    category: "Paper",
    icon: Package,
    customizable: false,
    details: "Essential disposable paper products for general hygiene, table service, and clean-up in restaurants, catering, and household settings.",
    images: [
      "/napkin-tissue-paper.jpg",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    specs: ["Ply: 1 Ply, 2 Ply, or 3 Ply options"],
  },
  {
    id: 10,
    name: "Areca & Bagasse Plates",
    description: "100% natural, biodegradable disposable tableware",
    image: "/areca-bagasse-plates-natural-fiber.jpg",
    category: "Plates",
    icon: Leaf,
    customizable: false,
    details: "Sturdy and stylish plates, bowls, and trays made from fallen Areca palm leaves or sugarcane pulp (Bagasse).",
    images: [
      "/areca-bagasse-plates-natural-fiber.jpg",
      "/disposable-eco-friendly-plates-bowls-natural-fiber.jpg",
    ],
    specs: ["100% Natural, No Chemicals or Wax Lining"],
  },
  {
    id: 11,
    name: "Hand Gloves & Bouffant Caps",
    description: "Disposable protective wear for hygiene and contamination control",
    image: "/hand-gloves-bouffant-caps.jpg",
    category: "Safety",
    icon: Zap,
    customizable: false,
    details: "Head and hand coverings essential for maintaining sanitary conditions in food service, healthcare, cleanrooms, and industrial environments.",
    images: [
      "/hand-gloves-bouffant-caps.jpg",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    specs: ["Gloves: Latex, Nitrile, Vinyl, or PE options"],
  },
  {
    id: 12,
    name: "Garbage Bags",
    description: "Waste disposal bags in various sizes and biodegradability options",
    image: "/garbage-bags-waste-management.jpg",
    category: "Bags",
    icon: Package,
    customizable: false,
    details: "Essential bags for collecting and disposing of garbage, offered in standard, oxo-biodegradable, and compostable types.",
    images: [
      "/garbage-bags-waste-management.jpg",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    specs: ["Biodegradable and Compostable Options Available"],
  },
]
