import { Package, Leaf, Droplet, Zap } from "lucide-react"

export const products = [
  {
    id: 1,
    name: "Bio Carry Bag & Pouches",
    description: "Biodegradable carry bags and pouches for eco-conscious packaging",
    image: "/biodegradable-carry-bags-pouches.jpg",
    category: "Customizable",
    icon: Package,
    customizable: true,
    details:
      "Premium biodegradable carry bags made from renewable resources. Perfect for retail, food service, and e-commerce businesses.",
    images: ["/biodegradable-carry-bags-pouches.jpg", "/eco-friendly-carry-bags.jpg", "/biodegradable-pouches.jpg"],
    specs: ["100% Biodegradable", "FDA Approved", "Custom Printing Available", "Various Sizes"],
  },
  {
    id: 2,
    name: "Brown Bag & Covers",
    description: "Kraft brown bags and protective covers for food and products",
    image: "/brown-kraft-paper-bags-covers.jpg",
    category: "Customizable",
    icon: Leaf,
    customizable: true,
    details:
      "Eco-friendly kraft paper bags with excellent durability and natural appearance. Ideal for bakeries, restaurants, and retail.",
    images: ["/brown-kraft-paper-bags-covers.jpg", "/kraft-paper-bags.jpg", "/brown-paper-covers.jpg"],
    specs: ["Kraft Paper", "Recyclable", "Grease Resistant", "Custom Sizes"],
  },
  {
    id: 3,
    name: "Bio Paper Cups & Containers",
    description: "Biodegradable paper cups and containers for beverages and food",
    image: "/biodegradable-paper-cups-containers.jpg",
    category: "Customizable",
    icon: Package,
    customizable: true,
    details: "Compostable paper cups and containers with food-grade coating. Perfect for hot and cold beverages.",
    images: ["/biodegradable-paper-cups-containers.jpg", "/paper-cups-biodegradable.jpg", "/food-containers-compostable.jpg"],
    specs: ["Compostable", "Food Grade", "Leak Proof", "Various Capacities"],
  },
  {
    id: 4,
    name: "PP, LDPE & BOPP Pouches",
    description: "Flexible plastic pouches in various materials for packaging",
    image: "/plastic-pouches-pp-ldpe-bopp.jpg",
    category: "Customizable",
    icon: Droplet,
    customizable: true,
    details: "Versatile plastic pouches available in multiple materials for different packaging needs.",
    images: ["/plastic-pouches-pp-ldpe-bopp.jpg", "/plastic-pouches-packaging.jpg", "/flexible-film-pouches.jpg"],
    specs: ["Multiple Materials", "Flexible Design", "Moisture Resistant", "Custom Printing"],
  },
  {
    id: 5,
    name: "Aluminium Container & Wraps",
    description: "Durable aluminium containers and wraps for food storage",
    image: "/aluminium-containers-wraps.jpg",
    category: "Containers",
    icon: Package,
    customizable: false,
    details:
      "Premium aluminium containers for food storage and transportation. Excellent heat retention and durability.",
    images: ["/aluminium-containers-wraps.jpg", "/aluminium-food-containers.jpg", "/metal-storage-containers.jpg"],
    specs: ["Durable Aluminium", "Heat Resistant", "Recyclable", "Various Sizes"],
  },
  {
    id: 6,
    name: "Plastic Container & Juice Cups",
    description: "Clear plastic containers and disposable juice cups",
    image: "/plastic-containers-juice-cups.jpg",
    category: "Containers",
    icon: Droplet,
    customizable: false,
    details: "Crystal clear plastic containers perfect for beverages, desserts, and food items.",
    images: ["/plastic-containers-juice-cups.jpg", "/clear-plastic-cups.jpg", "/disposable-juice-containers.jpg"],
    specs: ["Crystal Clear", "Disposable", "Leak Proof", "FDA Approved"],
  },
  {
    id: 7,
    name: "PET Container & Dessert Cups",
    description: "Transparent PET containers for desserts and food items",
    image: "/pet-containers-dessert-cups.jpg",
    category: "Containers",
    icon: Package,
    customizable: false,
    details: "High-quality PET containers ideal for desserts, pastries, and food display.",
    images: ["/pet-containers-dessert-cups.jpg", "/pet-dessert-containers.jpg", "/transparent-food-cups.jpg"],
    specs: ["PET Material", "Transparent", "Stackable", "Microwave Safe"],
  },
  {
    id: 8,
    name: "Wooden Cutlery & Paper Straw",
    description: "Eco-friendly wooden cutlery and biodegradable paper straws",
    image: "/wooden-cutlery-paper-straws.jpg",
    category: "Accessories",
    icon: Leaf,
    customizable: false,
    details: "Sustainable wooden cutlery and paper straws for eco-conscious food service.",
    images: ["/wooden-cutlery-paper-straws.jpg", "/wooden-cutlery-eco-friendly.jpg", "/placeholder.svg?height=400&width=400"],
    specs: ["100% Biodegradable", "Eco-Friendly", "Compostable", "Food Safe"],
  },
  {
    id: 9,
    name: "Napkin Tissue Paper",
    description: "Soft and absorbent napkin tissue paper for food service",
    image: "/napkin-tissue-paper.jpg",
    category: "Paper",
    icon: Package,
    customizable: false,
    details: "Premium quality napkin tissue paper for restaurants, cafes, and food service businesses.",
    images: [
      "/napkin-tissue-paper.jpg",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    specs: ["Soft & Absorbent", "Bulk Available", "Eco-Friendly", "Various Colors"],
  },
  {
    id: 10,
    name: "Areca & Bagasse Plates",
    description: "Natural fiber plates made from areca and bagasse materials",
    image: "/areca-bagasse-plates-natural-fiber.jpg",
    category: "Plates",
    icon: Leaf,
    customizable: false,
    details: "100% natural and compostable plates made from agricultural waste materials.",
    images: [
      "/areca-bagasse-plates-natural-fiber.jpg",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    specs: ["100% Compostable", "Natural Material", "Sturdy", "Microwave Safe"],
  },
  {
    id: 11,
    name: "Hand Gloves & Bouffant Caps",
    description: "Protective hand gloves and bouffant caps for food handling",
    image: "/hand-gloves-bouffant-caps.jpg",
    category: "Safety",
    icon: Zap,
    customizable: false,
    details: "Food-grade protective gloves and caps for hygiene and safety compliance.",
    images: [
      "/hand-gloves-bouffant-caps.jpg",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    specs: ["Food Grade", "Latex Free", "Disposable", "Various Sizes"],
  },
  {
    id: 12,
    name: "Garbage Bags",
    description: "Durable garbage bags for waste management and disposal",
    image: "/garbage-bags-waste-management.jpg",
    category: "Bags",
    icon: Package,
    customizable: false,
    details: "Heavy-duty garbage bags for commercial and residential waste management.",
    images: [
      "/garbage-bags-waste-management.jpg",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    specs: ["Heavy Duty", "Tear Resistant", "Various Sizes", "Bulk Available"],
  },
]
